### ISSUE TITLE
Ability to control the format

### ISSUE THREAD

**Issue by hishamco** [MuhammadMabrouk/jquery.hijri.date#1]
It would be nice to allow the developers controls the rendered output by supplying the date format for both Hijri & Gregorian dates

**Comment by MuhammadMabrouk** [comment]
@hishamco Thank you for suggesting improvements and additions to the 'jquery-hijri-date'. I welcome your involvement and will certainly consider implementing your idea in future updates.

**Comment by MuhammadMabrouk** [comment]
Hello brother Hisham,
I made a new update to "jquery-hijri-date" and added some options to control the rendered output.
Thanks for your suggestion again, have a nice day 💐
@hishamco

**Comment by hishamco** [comment]
Happy to head that, a best practice in GitHub to link the issue to the PR, so whenever its merged the issue will be closed and I will be notified that the issue has been fixed

Thanks again
