### ISSUE TITLE
Hijri Date is showing Wrong

### ISSUE THREAD

**Issue by TehsimAftab** [MuhammadMabrouk/jquery.hijri.date#2]
I am using your Hirji Date Script, Thank You So Much for such a valuable script. The date is 1 day behind. How to add +1 to it which part. Need your support and a quick response will be highly appreciated.

Thank You,

**Comment by MuhammadMabrouk** [comment]
Update to the new version of the plugin and add this option to your code:
`$('.my-date').hijriDate({ correction: +1 });`
@TehsimAftab
